// successCodes.ts
export const SuccessCodes = {
  // Operazioni generiche
  OPERATION_SUCCESSFUL: "OPERATION_SUCCESSFUL",
  REQUEST_PROCESSED: "REQUEST_PROCESSED",

  // Operazioni CRUD
  ENTITY_CREATED: "ENTITY_CREATED",
  ENTITY_UPDATED: "ENTITY_UPDATED",
  ENTITY_DELETED: "ENTITY_DELETED",
  ENTITY_RETRIEVED: "ENTITY_RETRIEVED",
  ENTITIES_LISTED: "ENTITIES_LISTED",

  // Autenticazione
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  SESSION_REFRESHED: "SESSION_REFRESHED",
  PASSWORD_RESET: "PASSWORD_RESET",

  // Utenti
  USER_REGISTERED: "USER_REGISTERED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  ACCOUNT_VERIFIED: "ACCOUNT_VERIFIED",

  // File
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DELETED: "FILE_DELETED",

  // Paginazione
  PAGE_RETRIEVED: "PAGE_RETRIEVED",

  // Ricerche
  SEARCH_COMPLETED: "SEARCH_COMPLETED",
  FILTER_APPLIED: "FILTER_APPLIED",

  // Notifiche
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  EMAIL_SENT: "EMAIL_SENT",
};
